security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        users_in_memory: { memory: null }
        backend_user_provider:
            entity:
                class: App\Entity\BackendUser
                property: username
        frontend_user_provider:
            entity:
                class: App\Entity\FrontendUser
                property: email
    firewalls:
        assets:
            pattern: ^/(|css|js)/
            security: false
        backend:
            pattern: ^/admin
            form_login:
                provider: backend_user_provider
                login_path: shop_backend_login
                check_path: shop_backend_login
                enable_csrf: true
            logout:
                path: backend_logout
        frontend:
            form_login:
                provider: frontend_user_provider
                login_path: shop_backend_login
                check_path: shop_backend_login
                enable_csrf: true
            logout:
                path: frontend_logout

    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
