version: '3'

services:
  database:
    container_name: database
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ChangeMe}
      POSTGRES_USER: ${POSTGRES_USER:-symfony}
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - '6969:5432'

  web:
    container_name: apache
    build:
      context: .
      dockerfile: ./.docker/apache/Dockerfile
    environment:
      VIRTUAL_HOST: ${HOST}
      PHP_SOCKET: symfony_php:9000
      WEB_PHP_SOCKET: symfony_php:9000
    volumes:
      - .:/var/www
    ports:
      - '8000:80'
    depends_on:
      - database
    networks:
      default:
        aliases:
          - ${HOST}

volumes:
  db-data:
