controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

backend_logout:
    path: /admin/logout
    methods: GET

frontend_logout:
    path: /logout
    methods: GET

home_page:
    path: /
    controller:    Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: templates/frontend/index.html.twig
        statusCode: 200
        maxAge: 86400
        sharedAge: 86400
        private: true
