controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

backend_logout:
    path: /admin/logout
    methods: GET

frontend_logout:
    path: /logout
    methods: GET